name: AI PR Review Bot_Raj
 
on:
 
  pull_request:
 
    types: [opened, synchronize, reopened]
 
jobs:
 
  review:
 
    runs-on: ubuntu-latest  # Or 'ubuntu-latest' for GitHub-hosted runner
 
    steps:
 
      - name: Checkout PR branch
 
        uses: actions/checkout@v4
        with:
          submodules: true
 
      - name: Install PR Bot
 
        working-directory: ./pr-agent
 
        shell: bash
 
        run: |
 
          pip install -e .
 
      - name: Run PR Review
 
        env:
 
          GITHUB__USER_TOKEN: ${{ secrets.AI_PR_REVIEW_BOT }}
 
          OPENAI__KEY: ${{ secrets.OPENAI_API_KE }}   
 
        working-directory: ./pr-agent
 
        shell: bash
 
        run: |

          python -c "import sys; from pr_agent.cli import run_command; try: run_command('${{ github.event.pull_request.html_url }}', 'review') except Exception as e: print(f'❌ PR Review failed: {e}'); sys.exit(1)"



