name: AI PR Review Bot_Raj
 
on:
 
  pull_request:
 
    types: [opened, synchronize, reopened]
 
jobs:
 
  review:
 
    runs-on: ubuntu-latest  # Or 'ubuntu-latest' for GitHub-hosted runner
 
    steps:
 
      - name: Checkout PR branch
 
        uses: actions/checkout@v4
        with:
          submodules: true
 
      - name: Install PR Bot
 
        working-directory: ./pr-agent
 
        shell: bash
 
        run: |
 
          pip install -e .
 
      - name: Run PR Review
        env:
          GITHUB__USER_TOKEN: ${{ secrets.AI_PR_REVIEW_BOT }}
          OPENAI__KEY: ${{ secrets.OPENAI_API_KE }}
        working-directory: ./pr-agent
        shell: bash
        run: |
          echo -e "import sys\nfrom pr_agent.cli import run_command\ntry:\n    run_command('https://github.com/Shiva-cal/django-oscar/pull/3', 'review')\nexcept Exception as e:\n    print(f'PR Review failed: {e}')\n    sys.exit(1)" | python



